version: '3'

services:
  server:
    build: .
    container_name: server
    ports:
      - "9001:9001"
    env_file:
      - ./local.env
    volumes:
      - ./credentials:/app/credentials
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - telescope
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend/playground
      dockerfile: Dockerfile
      args:
        - API_SERVER_URL
        - NUXT_PUBLIC_API_SERVER_URL
        - FORMKIT_PRO_LICENSE_KEY
        - GOOGLE_OAUTH_CLIENT_ID
        - GOOGLE_OAUTH_CLIENT_SECRET
        - AUTH_SECRET
        - CLERK_PUBLIC_KEY
        - NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        - CLERK_SECRET_KEY
        - NUXT_CLERK_SECRET_KEY
        - CLERK_DOMAIN
        - ALLOWED_DOMAINS
        - GTAG_ID
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/playground/local.env
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - telescope

  db:
    image: postgres:15
    container_name: db
    env_file:
      - ./local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - telescope

networks:
  telescope:
    driver: bridge

volumes:
  postgres_data: